kind: pipeline
type: docker
name: default

steps:
- name: build
  image: composer:2
  commands:
  - composer install --dev

- name: test
  image: php:8.2
  commands:
  - cp .env.testing .env
  - docker-php-ext-install mysqli pdo pdo_mysql
  - php artisan migrate
  - php artisan passport:install -q
  - php artisan test

services:
- name: mariadb
  image: mariadb:10.5
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: test_db_vinyls_collection
    MYSQL_USER: test
    MYSQL_PASSWORD: test
